apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../multus-common

patches:
- target:
    kind: DaemonSet
    name: kube-multus-ds
  patch: |-
    - op: add
      path: /spec/template/spec/priorityClassName
      value: system-node-critical

configMapGenerator:
  - name: multus-daemon-config
    namespace: kube-system
    # using merge to keep the default labels the configmap has,
    # but in practice the only field is the config that we're replacing, so `replace` would work too
    behavior: merge
    files:
      - daemon-config.json
