apiVersion: v1
kind: Pod
metadata:
  name: tcp-proxy
  labels:
    app: tcp-proxy
spec:
  containers:
    - name: tcp-proxy
      image: alpine/socat
      command: ["/bin/sh", "-c"]
      args:
        - |
          socat tcp-listen:8080,fork,reuseaddr tcp:10.244.1.45:8080 & \
          socat tcp-listen:6080,fork,reuseaddr tcp:10.244.1.45:6080 & \
          socat tcp-listen:8501,fork,reuseaddr tcp:10.244.1.45:8501 & \
          socat tcp-listen:5900,fork,reuseaddr tcp:10.244.1.45:5900
      ports:
        - containerPort: 8080
        - containerPort: 6080
        - containerPort: 8501
        - containerPort: 5900